spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1471...
            client-secret: GOCS...
            scope:
              - email
              - profile
jwt:
  issuer: aju...
  secret_key: study-springboot
